# Generated by Django 3.2.8 on 2021-11-04 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='static/images/banner', verbose_name='轮播图')),
                ('link_url', models.URLField(max_length=100, verbose_name='图片链接')),
                ('idx', models.IntegerField(verbose_name='索引')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('str1', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'blog_db_banner',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='博客分类名称')),
                ('str1', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
                'db_table': 'blog_db_blogcategory',
            },
        ),
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('link', models.URLField(default='', max_length=50, verbose_name='友情链接')),
                ('str1', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'db_table': 'blog_db_friendlylink',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='标签名称')),
                ('str1', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tags标签',
                'verbose_name_plural': 'Tags标签',
                'db_table': 'blog_db_tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=2, verbose_name='标签')),
                ('content', models.TextField(verbose_name='内容')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数')),
                ('cover', models.ImageField(default=None, upload_to='static/images/post/', verbose_name='博客图片')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐博客')),
                ('str1', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogcategory', verbose_name='博客分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '博客信息',
                'verbose_name_plural': '博客信息',
                'db_table': 'blog_db_post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pud_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('str1', models.CharField(max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post', verbose_name='该博客的评论信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'blog_db_comment',
            },
        ),
    ]
