# Generated by Django 3.2.8 on 2021-11-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='str1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='str1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='str1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='friendlylink',
            name='str1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='str1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tags',
            name='str1',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
